name: Dr. med. dent. CATHARINA KÖBLER
description: Zentrum für Oralchirurgie & Systemische Zahnheilkunde
logo: /images/logo.png
url: https://www.praxisdrkoebler.de
baseurl: ""
sass:
  style: :compressed
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    - praxisdrkoebler.iml
